version: '3.8'

networks:
  web_app:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dnet_web_app
    ipam:
      config:
        - subnet: 180.18.0.0/24
      driver: default
  datastore:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dnet_datastore
    ipam:
      config:
        - subnet: 180.18.1.0/24
      driver: default
services:
  server:
    image: amphitrite/server:0.0.1
    networks:
      web_app:
        aliases:
          - web_app.server
      datastore:
        aliases:
          - datastore.server
  client:
    image: amphitrite/client:0.0.1
    networks:
      web_app:
        aliases:
          - web_app.client
    ports:
      - "80:80"
  datastore:
    image: amphitrite/datastore:0.0.1
    networks:
      datastore:
        aliases:
          - datastore.datastore
