version: '3.3'
networks:
  web_app:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dnet_web_app
    ipam:
      config:
        - subnet: 181.18.0.0/24
      driver: default
  datastore:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dnet_datastore
    ipam:
      config:
        - subnet: 181.18.1.0/24
      driver: default
services:
  server:
    environment:
      AMPHI_JWT_SECRET_KEY: $${AMPHI_JWT_SECRET_KEY-}
    image: ${SERVER_IMAGE}
    networks:
      web_app:
        aliases:
          - web_app.server
      datastore:
        aliases:
          - datastore.server
  client:
    environment:
      AMPHI_JWT_SECRET_KEY: $${AMPHI_JWT_SECRET_KEY-}
    image: ${CLIENT_IMAGE}
    networks:
      web_app:
        aliases:
          - web_app.client
    ports:
      - "80:80"
  datastore:
    image: ${DATASTORE_IMAGE}
    networks:
      datastore:
        aliases:
          - datastore.datastore
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
