// Real data: 2025-2026 PCF LFS Spawning Summary — Egg Count Summary (imported via Egg Bowls).
// Funnel (eggs→live larvae) = clean per-bowl data. CURRENT_FISH uses only in-scope data
// (Larval Cohorts count + Fish Care); live head-counts are MISSING (no inventory import yet).
export const SEASON = '2025-2026';
export const SUMMARY = {"bowls": 64, "eggs": 144166, "hatched": 50253, "liveLarvae": 47567, "overallPct": 33.0, "lost": 6, "biggestDropLabel": "Eggs collected \u2192 Viable eggs (6 dpf)", "biggestDropCount": 57858, "biggestDropPct": 40.1};
export const FUNNEL = [{"stage": "Eggs collected", "count": 144166, "pct": 100.0, "note": "Spawned across 64 egg bowls"}, {"stage": "Viable eggs (6 dpf)", "count": 86308, "pct": 59.9, "note": "Fertilization + early egg viability"}, {"stage": "Hatched", "count": 50253, "pct": 34.9, "note": "Survived incubation"}, {"stage": "Live larvae (current)", "count": 47567, "pct": 33.0, "note": "Early larval survival \u2014 still rearing"}];
export const CURRENT_FISH = {"monitoring": "Monitored daily via Fish Care", "missingTitle": "Current live-fish counts \u2014 not yet in the system", "missing": "These cohorts are alive in the tanks now, but the system has no head count. Needs (1) a current-inventory import, and (2) a link from each larval cohort / egg bowl to its surviving fish \u2014 the larvae \u2192 alive-fish connection."};
export const LOSSES = [{"cross": 6, "egg_id": "EB6", "note": "Bowl turned over in sump; lost clutch"}, {"cross": 8, "egg_id": "EB8", "note": "Scrapped at 1dpf due to poor fertilization. Counted before scrapping"}, {"cross": 11, "egg_id": "EB11", "note": "Bowl turned over in sump; lost clutch"}, {"cross": 12, "egg_id": "EB12", "note": "Bowl turned over in sump; lost clutch"}, {"cross": 13, "egg_id": "EB13", "note": "Bowl turned over in sump; lost clutch"}, {"cross": 17, "egg_id": "EB17", "note": "Scrapped at 1dpf due to poor fertilization"}];
export const FUTURE_STAGES = [{"stage": "Reach breeding age", "note": "~2 yr \u2014 2026 fish breed ~2028"}, {"stage": "Successful reproduction", "note": "Produce viable next generation"}, {"stage": "Generational diversity (F, DI)", "note": "All current fish are WT founders"}];
